### ISSUE TITLE
Facing an issue when integrating Vipps Login with a react native app

### ISSUE THREAD

**Issue by SavantD** [vippsas/vipps-login-api#112]
Hello, 

What im trying to achieve is to integrate vipps login into my react native merchant app. currently i've developed the required logic from the client side and server side (java). Initially when clicking the "Login with Vipps" in my merchant react native app, it initiates the login flow by calling the constructed /auth url. So it opens-up an external browser with the Vipps screen that says "Opening Vipps" with a "Continue" button at the end. When i press the continue button it directs me to the phonenumber entering screen. When i enter the test phone number i was provided it gives me the below error.

"To log in with Vipps you need to have Vipps on your phone and be at least 15 years old". 

Please note that im testing this login flow on an android emulator (Samsung S8 API 28) and i also have installed the vipps app from the google app store correctly.  

The /auth url im calling is below (which is correctly redirecting me to the consent screen, but does not go further after entering the phone number)

url : https://apitest.vipps.no/access-management-1.0/access/oauth2/auth?client_id=<client_id_created_from_vipps_portal>&response_type=code&scope=openid+api_version_2&state=4d5dac27-d47e-4e7c-841b-760e3168d21b&redirect_uri=merchantappschema://vippscallback

Please have a look at the GIF i've attached herewith to get a more clear understanding of my issue. 

Hoping for a swift response from your team, since this feature is time critical for our merchant app release. Thanks
![vippsissueedited](https://user-images.githubusercontent.com/11026172/155736583-32ed199c-75e1-4abe-bb5d-ffa0f881a2fc.gif)
.

**Comment by jonkjenn** [comment]
Hi @SavantD the issue with not getting automatically switched to the Vipps app is probably related to it being run on a emulator, do you have the possibility to test on a real device? The phone number flow should work though. Have you successfully logged into the Vipps app using that account?

**Comment by SavantD** [comment]
Hello @jonkjenn Thanks for your response.

I did test this on a real device as well, but couldnt move forward from the telephone number input screen. entering the test phonenumber (which i got from my merchant app owner) gave me an error like "To log in with Vipps you need to have Vipps on your phone and be at least 15 years old"

I have installed vipps on this test device (Google Pixel), tried login-in to the vipps application using the above mentioned test phonenumber.  as shown in the screencap below getting this error.

![image](https://user-images.githubusercontent.com/11026172/156111479-2b6a0694-5d66-4230-a0af-e13e249b2384.png)

 Actually im developing this 'Login with Vipps' feature for my customer who is the merchant app owner. I dont have a BankID..
The development and testing work i've done so far was by using the  'clientid' and 'clientsecret' given to me by my customer(merchant app owner who has a BankID & account on vipps). I was also given a test user phonenumber and PIN to test the login flow. 

Do i need to login successfully into the Vipps app on my mobile first before testing the above flow? 

Since the above mentioned test phone number i received didnt work for me, what is the best approach you can suggest for when testing this scenario without using actual vipps credentials?

**Comment by SavantD** [comment]
@jonkjenn Nice! i will setup this test app and recheck the functionality. Thanks for pointing it out

**Comment by SavantD** [comment]
So after installing the test app the flow continued smoothly.  However seems like the callback url is not hitting my clientside callback code. I've configured and tested deeplinks to work properly with my react native app though.

Am i missing anything @jonkjenn ?

This is my initial auth url: 

https://apitest.vipps.no/access-management-1.0/access/oauth2/auth?client_id=client_id&response_type=code&scope=openid+api_version_2&state=random_state_value&redirect_uri=bagid://vippscallback

as you see the redirect_uri is set to bagid://vippscallback in the portal.vipps.no

**Comment by SavantD** [comment]
UPDATE => 

I've managed to get the "login with vipps" working correctly now. tested and verified this on an android emulator.
Apparently there was a bug in my callback interception logic. My bad. Worked well after fixing it. the login flow works even without the params 'requested_flow' and 'app_callback_uri' in react-native. Switches back'n' forth correctly from external browser to the merchant app.
