### ISSUE TITLE
Huawei: Switch til app etter login skjer ikke automatisk 

### ISSUE THREAD

**Issue by bjornreppen** [vippsas/vipps-login-api#113]
Tester Vipps Login på Huawei P40 fysisk device med cloud debugging i https://developer.huawei.com uten at Vipps er installert på samme enhet.
P40 (og antagelig en del andre modeller) har her Huawei Browser v12.0.1.302 som standard nettleser. Etter pålogging vises bare i et veldig kort glimt notification:

![image](https://user-images.githubusercontent.com/281359/156550457-c9e47121-ea2c-405f-a135-991a6a9ed192.png)

Så forsvinner notification og man ser bare en liten notification i toppen. 

![image](https://user-images.githubusercontent.com/281359/156549052-d4550955-1c93-42e2-98fe-e8597ae240ab.png)

Før det i løpet av veldig kort tid bare er en liten blå bjelle som gir hint om at brukeren må gjøre noe:

![image](https://user-images.githubusercontent.com/281359/156549289-363bc842-dd9b-45e5-8495-079d3b487884.png)

Der blir man hengende hvis man ikke legger til den lille bjella og aktivt går og trykker på den.

Er det noen måte å forbedre brukeropplevelsen på i disse tilfellene?

**Comment by cloveras** [comment]
Hei fra Vipps!

Vi undersøker dette.

Skjer dette bare på Huawei-telefonen?

Christian

**Comment by bjornreppen** [comment]
Ja, er bare kjent med at det er problem på Huawei og for de som ikke har erstattet Huawei sin browser og heller ikke har Vipps "lokalt" så det er nok et begrenset antall som kan slite litt med å komme seg inn.

**Comment by cloveras** [comment]
Hei, og beklager elendig oppfølging

Etter det jeg kan se, er dette ikke et generelt problem med Android, men noe sm bare skjer på (enkelte?) telefoner fra Huawei. 

Det er dessverre ikke noe vi kan gjøre for å endre på dette, beklager.
