### ISSUE TITLE
Migrating user ids?

### ISSUE THREAD

**Issue by thoraj** [vippsas/vipps-login-api#231]
Our business has taken over a software solution from a company where there are lots of customer have enabled VIPPS login. This means that there is a mapping between VIPPS issued sub claims and the local user ids. 

Since the old company is defunct, the VIPPS account for the business will be disabled. Therefore we have integrated the solution with a new VIPPS account for our own business.

The issues is that now none of the Vipps login work. This is likevly because the user sub claim has changed between the Vipps company accounts. 

How can we, or VIPPS, make it so that the same individual will get the same sub-claim as he did in the old Vipps account?

**Comment by cloveras** [comment]
Hello!

The `sub` is documented in the FAQ: https://developer.vippsmobilepay.com/docs/APIs/login-api/vipps-login-api-faq/ .. and also in the rest of the API documentation: https://developer.vippsmobilepay.com/docs/APIs/login-api/

Sounds like you need to ask all the users to log in again, and "silently" map the old `sub` to the new `sub` so the user's don't notice.

**Comment by thoraj** [comment]
Thanks for the quick reply. I feared this would be the answer. 

And it was also new to me that even within the same Vipps Business Account, the sub is not stable. It will change when the user changes phone number, thus breaking the mapping to his local account and his login. 

This is the reason we need a stable identifier such as the NIN

**Comment by cloveras** [comment]
The `sub` stays the same for the MSN (the sales unit). 

Please note that the `sub` si related to consent. It is not intended as a replacement for NIN or any other unique identifier of the user.

We collected a few different entries related to `sub` in the Login FAQ into one today: https://developer.vippsmobilepay.com/docs/APIs/login-api/vipps-login-api-faq/#what-is-the-sub
