### ISSUE TITLE
Authorize flow fails on Apple devices when Vipps is not installed

### ISSUE THREAD

**Issue by dagsunde** [vippsas/vipps-login-api#35]
Having a "Log in with vipps" site, or app on an Apple device, using Safari:

using a call to "https://api.vipps.no/access-management-1.0/access/oauth2/auth?client_id=xxxxxxxxx&scope=openid%20name&state=1294u01924u0192&response_type=code&redirect_uri=https://solver.no"

causes safari to report an error to the user if the Vipps App isn't installed.
Apple refuses to clear our apps, as long as the callback from your Authorice endpoint causes an error in Safari...
This is by design from Apple.

to reproduce: download and install our app on a iPhone or iPad *without Vipps installed.
(https://apps.apple.com/no/app/solverapp/id1498196167)

...or, open https://qr.solver.no in Safari, and try to log in with Vipps on an Apple device.
(Or any other site that use "Log in with Vipps")

another example:
https://nattogdag.no/vi-har-digitalisert-hele-arkivet/?redirect_to=https%3A%2F%2Fnd.no%2Farkivet%2F

**Comment by cloveras** [comment]
Hi

As far as I know, Apple does not approve apps that require another app to work correctly.

This also applies to apps that provider payment: If the only payment method is Vipps, Apple will not approve the app.

Does this help..?

Christian, Vipps

**Comment by dagsunde** [comment]
That's not quite the problem.

We have spoken to Linda at Vipps, pleas call us at 90759320

Thanks...

**Comment by cloveras** [comment]
Hi again

Sorry for misunderstanding. Vidar, product owner for Vipps Login, will call you.

It seems you have contacted customer service, sent an email to integration@vipps.no _and_ created this issue. We are able to help faster if we get one request, otherwise we risk that multiple people work in parallell, trying to solve the same problem.

Christian, Vipps

**Comment by dagsunde** [comment]
My Bad... Sorry for the mess!

Thank you for all the help, from all of you!
