### ISSUE TITLE
retrieving userinfo after payment

### ISSUE THREAD

**Issue by Jay932187483** [vippsas/vipps-login-api#39]
I have received a "sub"-key after a payment with scope set and are trying to retrieve the customers userinfo.

Documentation says
do a POST to https://apitest.vipps.no/oauth2/token
with the x-www-form-urlencoded data "grant_type=client_credentials"
and the base64-concenated http authorization header of clientid:secret

However I get 404 Resource not found. I seem to also get 404 if I use an incorrect clientid.
The client/secret is the same ones used to make the payment. I also tried without using newline \n in the base64 data.
The only http headers added is content-type and authorization. Vipps login is activated on the test-user

Is there a way to get more information about what is wrong ?
Thanks

**Comment by Jo-Inge** [comment]
Hi!
Looks like you are missing part of the url to this endpoint. The url can be found under "token_endpoint" by following [Openid connect discovery endpoint](https://github.com/vippsas/vipps-login-api/blob/master/vipps-login-api.md#openid-connect-discovery-endpoint).

**Comment by Jay932187483** [comment]
Indeed I was missing a part of the url. Got it working now :+1: 
The recurring developer documentation could be slightly updated I think.
The complete URL can be taken from the openid-configuration request
The base64 authorization is excluded newline, so the command 

echo "client:secret"|base64

will result in incorrect basic token.

It should be
echo -n "client:secret"|base64
