### ISSUE TITLE
Switch user is not possible without deleting cookies from api.vipps.no

### ISSUE THREAD

**Issue by steffanhalv** [vippsas/vipps-login-api#53]
If 'Husk meg i denne nettleseren' is checked, vipps will always login using this user & it's not possible to login using another phone number without deleting browser cache from api.vipps.no.

<img width="466" alt="Skjermbilde 2021-01-29 kl  14 13 23" src="https://user-images.githubusercontent.com/4593184/106279527-d5d50780-623c-11eb-9c0e-cb1a52c62e60.png">

Instead of just autologin it should show a confirm window like 'Continue as xxx or continue using another phone number'. This also how other login providers does this, like google, microsoft, facebook etc.

Means this flow needs another step in the middle with a confirm login button and a 'or login using another phonenumber' button:
<img width="563" alt="Skjermbilde 2021-01-29 kl  14 18 02" src="https://user-images.githubusercontent.com/4593184/106279609-fa30e400-623c-11eb-9932-2191eb0a4096.png">

**Comment by VidarHolm** [comment]
Hi! 

Thank you for your input! 

We recommend our users to only choose to be remembered in a browser on personal devices (devices that is not used by others). If a user would like to switch to a different user in a browser or logout from a browser, our primary channel to do so is to go into the Vipps-app - Profile and Personal information to administer their browsers from there (the user can see and log out from browsers there). 

Regards
Vidar

**Comment by steffanhalv** [comment]
I did not know you could log out from browsers from the app, thats great news.
But that is still not accessible for the user trying to login, because the user logged in before would have to do that.

So in my opinion a confirm button is preferred as not all people do know how to delete browser cookies. 😅

**Comment by cloveras** [comment]
Hi @steffanhalv 

The text in your screenshot says that: "In Vipps you can se and remove browsers that remember you".

Vidar can probably say more about our thought around some sort of "Not you? Click here" functionality.

Christian, Vipps

**Comment by VidarHolm** [comment]
The reason why we do not support a "Not you" functionality is that we recommend our users to only choose to be remembered in a browser on personal devices (devices that is not used by others). This means that few users should come into a state where they are able to login as others and thus need others to logout before they can login as themselves. 

If we where to introduce a "Not you" functionality we would need to add friction to the login process for the majority of users, to be able to handle a not recommended use-case for a limited number of users. We have not gotten any feedback from our customer service that users in normal use have difficulties with this so far. If we start so see a broader need for this we will of course consider changes.

We are aware that while performing integration with and testing Vipps login the way to use the service will differ from normal everyday use. This can effect the use-cases and features that seem relevant.

Again, thank you for your feedback and thoughts! If you have other input or see that your customers struggle with the current "remembered in browser" features when you are in production we would like to hear back from you. 

Regards
Vidar
