### ISSUE TITLE
Client Credentials code example does not compile and uses non-standard library

### ISSUE THREAD

**Issue by holgerl** [vippsas/vipps-login-api#55]
In the Vipps Login API documentation, there is an example given for constructing the Base64-string for client credentials:

```
var client_id = 123456-test-4a3d-a47c-412136fd0871
var client_secret = testdzlJbUZaM1lqODlnUUtrUHI=

var wordArrayAzp = CryptoJS.enc.Utf8.parse(client_id + ":" + client_secret);
var client_authorization = CryptoJS.enc.Base64.stringify(wordArrayAzp);
```

But the code is missing quotes around the strings. And, more importanly, it uses a library `CryptoJS` that is unnecessary, as there are built in methods for base 64 encoding in both client and Node. A better code example would be:

**In node.js:**
```
var client_id = "123456-test-4a3d-a47c-412136fd0871";
var client_secret = "testdzlJbUZaM1lqODlnUUtrUHI=";

var buffer = Buffer.from(client_id + ":" + client_secret, "utf-8");
var client_authorization = buffer.toString("base64");
```

**Or in the browser:**
```
var client_id = "123456-test-4a3d-a47c-412136fd0871";
var client_secret = "testdzlJbUZaM1lqODlnUUtrUHI=";

var client_authorization = btoa(client_id + ":" + client_secret);
```

**Comment by cloveras** [comment]
Hi @holgerl 

Thanks for this! We'll let the developers have a look, and update here ASAP.

Christian, Vipps
