### ISSUE TITLE
Callback URL to include # e.g https://mysite.com/#/callback

### ISSUE THREAD

**Issue by erlendoverby** [vippsas/vipps-login-api#57]
I'm developing a SPA using VueJS, and would like to avoid using History mode in the router. And when not using history mode the default is that URL's are with #.
However when I try to assign a callback URL eg. https://myspa.com/#/callback
I get an error from the admin console when I try to add a callback URL with hash.

I have implemented solutions with other OpenID providers where assigning a callback using hash is not a problem?

Would it be possible for Vipps to support callbacks with # as part of the URL.

Cheers
Erlend

**Comment by cloveras** [comment]
Hi @erlendoverby 

I don't know much about VueJS, but when you say "I get an error from the admin console": That's not an error from Vipps, is it? Where is this admin console?

Do you get any errors from our API? If so: Please post the complete request (snip the secrets) and reaponse. 

Christian, Vipps

**Comment by cloveras** [comment]
Hi again @erlendoverby 

It's not allowed to use '#' in the OAuth spec: https://tools.ietf.org/html/rfc6749#section-3.1.2

Christian, Vipps

**Comment by stian-svedenborg-gul-katt** [comment]
Hi yet again @erlendoverby 

You can get the behaviour you want (without changing the router) by setting the callback URI to an endpoint in your backend and redirect to the correct front-end view in the response. In general we recommend this approach as it prevents any rogue JS from intercepting the authorization_code in flight.

Best regards
Stian, Vipps

**Comment by erlendoverby** [comment]
Great - thanks - I 'll update my code and will make suggested changes.
