### ISSUE TITLE
register an account with vipps

### ISSUE THREAD

**Issue by trygvesu** [vippsas/vipps-login-api#68]
Hello, i am a novice when it comes to vipps and coding in general.
So my question will probably reveal that too. 
I am trying to integrate Login with vipps in my webshop.
However i get the message:

"Uff da, noe gikk galt
Error: invalid_request

The "redirect_uri" provided with your request does not match any of your preregistered URIs. See how to add/update URIs in our documentation:"

In the redirect url i just put the url to my webshop: 
https://webshopdotno.no

Is there any rules, syntax or specific page setup to meet the demand of the redirect url?

**Comment by jonkjenn** [comment]
Hi, you can find the requirements here https://github.com/vippsas/vipps-login-api/blob/master/vipps-login-api-faq.md#what-are-the-requirements-for-redirect-uris.
