### ISSUE TITLE
Test user account

### ISSUE THREAD

**Issue by marlonpm** [vippsas/vipps-login-api#80]
We were able to access the Vipps portal in our organization, we were able to integrate the login API into our app
and also test authentication with our test user.

The authentication process in the browser (phone and desktop) was going well when the developers tested it with the Test Vipps app on Android. Then, we installed the Test Vipps app on the iPhone for the same user, and after that, things stopped working.
It seems that is not longer pushing correctly the notifications to the app.

It will be nice to have multiple tests users. 
However, it might be a scenario where a person has Vipps installed in two different OS. 

Is this a limitation in the test environment? how to fix it?

**Comment by cloveras** [comment]
Hi @marlonpm

Please see: https://github.com/vippsas/vipps-developers/blob/master/vipps-test-environment.md#about-the-test-environment

>Push alerts may be unstable. To see payment requests: Open Vipps and manually go to the "Betalinger" (in English: "Payments") at the bottom of the main screen.

Christian, Vipps

**Comment by marlonpm** [comment]
Hi @cloveras,

Thank you for letting me know!

The alerts are working again.

Marlon
