### ISSUE TITLE
Is it possible to have multiple test user accounts?

### ISSUE THREAD

**Issue by Bossloven** [vippsas/vipps-login-api#82]
We only have one test user account on the Vipps Login test environment. We have the need to have multiple?

Best regards
Bård

**Comment by cloveras** [comment]
Hi

Yes. Please send an email, since we can not post it here. 

See: https://github.com/vippsas/vipps-developers/blob/master/contact.md

Christian, Vipps

**Comment by Bossloven** [comment]
Hi,
To be fair your link does not give me an answer. The overview is not user friendly, and to say the least there is no obvious email - other than a partnership email - which we are not at the moment. However there is a link to a form to request what we need help with - I think. Thus we have filled out a form - hopefully it is the correct communication channel.

Best regards
Bård - DNV

**Comment by cloveras** [comment]
Hi @Bossloven 

If you are a Vipps partner the email address is partnberbestilling@vipps.no.

If you are not a Vipps partner, but a regular merchant, the email address for technical questions is integration@vipps.no.

Christian, Vipps
