### ISSUE TITLE
401 - unauthorized on token exchange 

### ISSUE THREAD

**Issue by JohnSimonsen** [vippsas/vipps-login-api#97]
We are using the oidc-client-ts library to handle our requests. ( https://github.com/authts/oidc-client-ts )
and Vue + Typescript. 
Our vipps is configured to use: `client_authentication: client_secret_post`

Asuming the the Vipps flow should work as follows: 

- Call to authorize endpoint with a code_challenge
- (after login) Vipps Redirect to Callback endpoint with auth code
- library should do the token exchange by calling the oAuth/token endpoint (using the code_verifier matching the code_challenge) 

We have succesfully managed to use the library and our setup with our own OIDC authority. 

But when using together with vipps we receive an 401 - unauthorized on the vipps token call. With response: 
```
error: "invalid_client"
error_description: "Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)."
```
We are struggling to understand how the authorization can fail, we have checked everything we can think of.
We have checked PKCE by verifying that:
 - A code_challenge is POSTed on the authorize call
 - The code_verifier on the POST to the token endpoint matches the code_challenge
   - code_challenge = Base64(SHA256(code_verifier)) 
  
Even when the PKCE challenge matches, we stillget 401 on the Token Endpoint.

**Comment by thormarius** [comment]
> Our vipps is configured to use: `client_authentication: client_secret_post`

Haven't looked into this in detail yet and I'm uncertain on what `client_id` you're using, but I assume that this statement means that you've changed your configuration in https://portal.vipps.no in the correct environment according to https://github.com/vippsas/vipps-login-api/blob/master/vipps-login-api-faq.md#how-can-i-use-client_secret_post-for-authentication ?

**Comment by thoraj** [comment]
I'm working with @JohnSimonsen on this, so I'll chime in: 

We are able to do the described flow using the Postman requests provided in the VIPPS docs. However this seems to not use PKCE and does not provide a code_challenge when starting the flow. And so the call to /token use basic auth to authenticate the call. This works OK. But require the client code to know the client_secret.

We wish to use PKCE, and in fact the library we use oidc-client-ts) insist on providing a code_challenge parameter when using the 'code' grant_type. 

After logging in, we get the callback to the redirect_uri as expected, and the library tries to do a code exchange by POSTing to the /token endpoint. This post does not have any Authorization header or client secret in the payload. Instead it contain a code_verifier parameter which match the initial code_challenge parameter. 

However the POST to /token fails with 401. 

Shouldn't the code_verifier parameter be sufficient to authorize the /token call?

**Comment by thormarius** [comment]
Also closing this since I understand it to be the same issue as [#98](https://github.com/vippsas/vipps-login-api/issues/98)
