### ISSUE TITLE
Which types of authentication methods are supported for the /token endpoint

### ISSUE THREAD

**Issue by thoraj** [vippsas/vipps-login-api#98]
This question is related to #97 

Which types of authentication methods are supported for the /token endpoint? 

The .well-known metadata says: 

![image](https://user-images.githubusercontent.com/1554235/147070325-9c2ff818-f613-4c33-9e01-44189dab673d.png)

With `none` supported we would expect the code+PKCE flow described in #97 to work?

The api docs at  https://vippsas.github.io/vipps-login-api/shins/index.html#tocs_wellknown says:

![image](https://user-images.githubusercontent.com/1554235/147073070-6968a5fb-b4d2-4600-ac57-0560cdbcecfa.png)

So the docs and the well-known metadata disagrees about the `none` and `client_secret_jwt` methods. 

* If `none` is supported, we are either doing something wrong in #97, or the support is broken?
  - How do we specify `none`. The only options in the portal are `client_secret_post` and `client_secret_basic`

Even though it is unclear if client_secret_jwt or `private_key_jwt` are supported, neither are suitable for a public client such as our SPA.

**Comment by thormarius** [comment]
Okey, now I understand a bit more what you're trying to do @thoraj. The short (and embarrassing) answer here is that Vipps Login currently _only_ supports `client_secret_basic` and `client_secret_post` as token endpoint authentication methods, meaning that you must send the `/token` request from your backend. 

Our documentation, and especially our openid configuration, has unfortunately _not_ been clear on this. We will take action to update the documentation to reflect this. 

We have considered what it would take from us to support `none`, and concluded that this is something we cannot do right away. I is a feature we will look into some time in the future, but there are a few hurdles to it on our side that we need to sort out first.
