### ISSUE TITLE
JWT token validation in login flow

### ISSUE THREAD

**Issue by jacekelgda** [vippsas/vipps-login-api#99]
Hi. We are integrating with login-api at the moment and I found out that the access_token granted using `oauth2/token` endpoint is not a JWT token ( as stated in docs: https://github.com/vippsas/vipps-login-api/blob/master/vipps-login-api.md#access-token ). The only JWT token passed in response is id_token, which is also explained in the doc.

My question is - what is the best way to validate the token of request to our API from authenticated ( with vipps ) app client, since it is considered a bad practice to pass id_tokens in request. Our preferred way is to use jwks endpoint to validate token in request ( similar to Auth0 approach ).

**Comment by thormarius** [comment]
Not sure I understand exactly your use case here, but I'll try to answer. 

The access token is as you state correctly _not_ a jwt. It is not encoding any information and it's only purpose is to access our `/userinfo` endpoint to retrieve user data after a successful login. It cannot be used to validate requests towards your API (if that's what you're implying).

As for id_token verification: The ID you receive from us _can_ be verified by using they keys published in our jwks endpoint: https://api.vipps.no/access-management-1.0/access/.well-known/jwks.json

**Comment by jacekelgda** [comment]
yes, thank you
